### ISSUE TITLE
socket.gaierror: [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by pelcasandra** [yorokobicom/agent#15]
When I try to setup the agent and enter the license key I get the following error.

```
Enter your license Key below.
License key: sdsd
Please wait, attempting to authenticate your license...
Traceback (most recent call last):
  File "/usr/local/bin/yorokobi", line 11, in <module>
    load_entry_point('yorokobi==0.1.0', 'console_scripts', 'yorokobi')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/yorokobi-0.1.0-py3.7.egg/yorokobi/cli.py", line 148, in setup_agent
  File "/usr/local/lib/python3.7/site-packages/yorokobi-0.1.0-py3.7.egg/yorokobi/agent.py", line 417, in configure_agent
  File "/usr/local/lib/python3.7/site-packages/yorokobi-0.1.0-py3.7.egg/yorokobi/license.py", line 76, in identify_agent
  File "/usr/local/lib/python3.7/site-packages/yorokobi-0.1.0-py3.7.egg/yorokobi/license.py", line 35, in register_agent
socket.gaierror: [Errno -2] Name does not resolve
```

**Comment by Sonkun** [comment]
Can't reproduce that issue.

```
Enter your license Key below.
License key: sdsd
Please wait, attempting to authenticate your license...
The License key given does not exist in our records.
error message returned is: { "errors": [{ "type": "access_denied", "title": "HTTP Basic: Access denied." }] }
Retry? [Y/n]
```

That seems like a DNS error. Did you try pinging the yorokobi domain names on that machine ?
Could you copy paste the logs agent side ?

**Comment by pelcasandra** [comment]
I was getting this error using Docker and `improvements` branch following the instructions below.

```
docker build -t yorokobi .
docker run -d --name yorokobi --network=host yorokobi
docker exec -it yorokobi yorokobi setup
```

I just removed `--network=host` and it works fine now. 

This is how it ended up looking like.

```
docker build -t yorokobi .
docker run -d --name yorokobi yorokobi
docker exec -it yorokobi yorokobi setup
```

**Comment by Sonkun** [comment]
Ah. Sorry about the wrong parameter, I thought it was required.
