### ISSUE TITLE
Start yorokobi after installation

### ISSUE THREAD

**Issue by pelcasandra** [yorokobicom/agent#6]
After installing the agent, [set up daemon to start a boot](#4 ) and [start the daemon](#1 ) execute `yorokobi` command to begin with authentication and configuration.

**Comment by Sonkun** [comment]
After installing the package, the user has to type: 

```
sudo snap install yorokobi
yorokobi setup
```

**Comment by pelcasandra** [comment]
I just tried a fresh install of yorokobi snap but it seems the daemon is not starting on setup. 

```
martin@martin-VirtualBox:~$ sudo snap install yorokobi --edge
[sudo] password for martin: 
yorokobi (edge) 0+git.3b97c72 from 'martincaetano' installed
martin@martin-VirtualBox:~$ yorokobi setup
The agent doesn't appear running; ensure the agent is started.
```

```
martin@martin-VirtualBox:~$ sudo snap start yorokobi.daemon
Started.
martin@martin-VirtualBox:~$ sudo snap services
Service          Startup  Current
yorokobi.daemon  enabled  inactive
```

journalctl log

```
ene 19 02:55:53 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Scheduled restart job, restart counter is at 4.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit snap.yorokobi.daemon.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
ene 19 02:55:53 martin-VirtualBox systemd[1]: Stopped Service for snap application yorokobi.daemon.
-- Subject: Unit snap.yorokobi.daemon.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit snap.yorokobi.daemon.service has finished shutting down.
ene 19 02:55:53 martin-VirtualBox systemd[1]: Started Service for snap application yorokobi.daemon.
-- Subject: Unit snap.yorokobi.daemon.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit snap.yorokobi.daemon.service has finished starting up.
-- 
-- The start-up result is RESULT.
ene 19 02:55:54 martin-VirtualBox audit[2476]: AVC apparmor="DENIED" operation="open" profile="snap.yorokobi.daemon" name="/proc/2476/mounts" pid=2476 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
ene 19 02:55:54 martin-VirtualBox audit[2476]: AVC apparmor="DENIED" operation="create" profile="snap.yorokobi.daemon" pid=2476 comm="python3" family="inet6" sock_type="stream" protocol=0 requested_mask="create" denied_mask="create"
ene 19 02:55:54 martin-VirtualBox audit[2476]: AVC apparmor="DENIED" operation="open" profile="snap.yorokobi.daemon" name="/proc/2476/mounts" pid=2476 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
ene 19 02:55:54 martin-VirtualBox kernel: kauditd_printk_skb: 4 callbacks suppressed
ene 19 02:55:54 martin-VirtualBox kernel: audit: type=1400 audit(1547877354.632:441): apparmor="DENIED" operation="open" profile="snap.yorokobi.daemon" name="/proc/2476/mounts" pid=2476 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]: The Yorokobi agent is starting.
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]: Configuration file is '/var/snap/yorokobi/75/yorokobi.conf'
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]: Log file is '/var/snap/yorokobi/75/yorokobi.log'
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]: Traceback (most recent call last):
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/bin/yorokobid", line 11, in <module>
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     load_entry_point('yorokobi==0.1.0', 'console_scripts', 'yorokobid')()
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/lib/python3.5/site-packages/click/core.py", line 764, in __call__
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     return self.main(*args, **kwargs)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/lib/python3.5/site-packages/click/core.py", line 717, in main
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     rv = self.invoke(ctx)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/lib/python3.5/site-packages/click/core.py", line 956, in invoke
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     return ctx.invoke(self.callback, **ctx.params)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/lib/python3.5/site-packages/click/core.py", line 555, in invoke
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     return callback(*args, **kwargs)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/lib/python3.5/site-packages/yorokobi/cli.py", line 88, in run_agent
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     agent = Agent(config, config_filename, log_filename)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/lib/python3.5/site-packages/yorokobi/agent.py", line 56, in __init__
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     file_handler = logging.FileHandler(log_filename)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/usr/lib/python3.5/logging/__init__.py", line 998, in __init__
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     self.baseFilename = os.path.abspath(filename)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/usr/lib/python3.5/posixpath.py", line 357, in abspath
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     if not isabs(path):
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:   File "/snap/yorokobi/75/usr/lib/python3.5/posixpath.py", line 64, in isabs
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]:     return s.startswith(sep)
ene 19 02:55:54 martin-VirtualBox yorokobi.daemon[2476]: AttributeError: 'PosixPath' object has no attribute 'startswith'
ene 19 02:55:54 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Main process exited, code=exited, status=1/FAILURE
ene 19 02:55:54 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Failed with result 'exit-code'.
ene 19 02:55:54 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Service hold-off time over, scheduling restart.
ene 19 02:55:54 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit snap.yorokobi.daemon.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
ene 19 02:55:54 martin-VirtualBox systemd[1]: Stopped Service for snap application yorokobi.daemon.
-- Subject: Unit snap.yorokobi.daemon.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit snap.yorokobi.daemon.service has finished shutting down.
ene 19 02:55:54 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Start request repeated too quickly.
ene 19 02:55:54 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Failed with result 'exit-code'.
ene 19 02:55:54 martin-VirtualBox systemd[1]: Failed to start Service for snap application yorokobi.daemon.
-- Subject: Unit snap.yorokobi.daemon.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit snap.yorokobi.daemon.service has failed.
```

**Comment by pelcasandra** [comment]
I tried again now that the snap is using the correct version of remofile but still `yorokobi setup` is not starting the service.

```
martin@martin-VirtualBox:~$ yorokobi setup
The agent doesn't appear running; ensure the agent is started.
```
