### ISSUE TITLE
Update config and log file paths

### ISSUE THREAD

**Issue by pelcasandra** [yorokobicom/agent#8]
The current config and log files are saved at `~/yorokobi.conf` and `~/yorokobi.log`. 

Make sure they are saved at `/etc/yorokobi.conf` and `/var/log/yorokobi.log`.

**Comment by Sonkun** [comment]
This should be covered by the Debian package which installs the agent system-wide. The system service file runs the agent daemon (`yorokobid`) with the proper `--conf` and `--log` flags. 

See #1

**Comment by Sonkun** [comment]
Not sure where they are, snap seems to do so much stuff under the hood without documenting. Snaps run in isolated environment, so not using `--conf` and `--log` is fine. that said, need to know where they are

**Comment by pelcasandra** [comment]
Snap uses these paths: 

    /var/snap/yorokobi/current/yorokobi.conf
    /var/snap/yorokobi/current/yorokobi.log

I was able only to find the `yorokobi.conf` there. I couldn't see the `yorokobi.log` because I couldn't start the service. 

See this bug below (you can check these logs with `journalctl -xe`).

```
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]: The Yorokobi agent is starting.
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]: Configuration file is '/var/snap/yorokobi/101/yorokobi.conf'
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]: Log file is '/var/snap/yorokobi/101/yorokobi.log'
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]: Traceback (most recent call last):
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/bin/yorokobid", line 11, in <module>
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     load_entry_point('yorokobi==0.1.0', 'console_scripts', 'yorokobid')()
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/lib/python3.5/site-packages/click/core.py", line 764, in __call__
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     return self.main(*args, **kwargs)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/lib/python3.5/site-packages/click/core.py", line 717, in main
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     rv = self.invoke(ctx)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/lib/python3.5/site-packages/click/core.py", line 956, in invoke
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     return ctx.invoke(self.callback, **ctx.params)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/lib/python3.5/site-packages/click/core.py", line 555, in invoke
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     return callback(*args, **kwargs)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/lib/python3.5/site-packages/yorokobi/cli.py", line 88, in run_agent
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     agent = Agent(config, config_filename, log_filename)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/lib/python3.5/site-packages/yorokobi/agent.py", line 56, in __init__
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     file_handler = logging.FileHandler(log_filename)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/usr/lib/python3.5/logging/__init__.py", line 998, in __init__
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     self.baseFilename = os.path.abspath(filename)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/usr/lib/python3.5/posixpath.py", line 357, in abspath
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     if not isabs(path):
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:   File "/snap/yorokobi/101/usr/lib/python3.5/posixpath.py", line 64, in isabs
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]:     return s.startswith(sep)
ene 23 17:59:07 martin-VirtualBox yorokobi.daemon[19317]: AttributeError: 'PosixPath' object has no attribute 'startswith'
ene 23 17:59:07 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Main process exited, code=exited, status=1/FAILURE
ene 23 17:59:07 martin-VirtualBox systemd[1]: snap.yorokobi.daemon.service: Failed with result 'exit-code'.
```
